sudo: required
services: 
  - docker

before_install: 
  - docker build -t mwizerwa77/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true mwizerwa77/docker-react npm run test -- --coverage

  deploy: 
    provider: heroku
    api_key: 
      secure: d01a8278-dcb3-4b5a-9937-97020761e499
    app: dock-app
    on:
      repo: mwizerwa77/docker-react